# Site settings
title: Neil bantoc
email: neilbantoc@gmail.com
author: nbantoc

keywords: android, ux
description: Android enthusiast since Froyo. UX Engineer in the making.

# Only use this if you are serving your site via Github Pages
github:
  url: "https://neilbantoc.github.io"

# github:
#   url: "http://localhost:4000"

header: images/logo-white.png

# Formspree contact Form
# contact_form: ""


# Exclude our ruby stuff
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]


# Build settings
markdown: kramdown

theme: starving-artist-jekyll-theme
  
# Plugins
gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

collections:
  - galleries

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
# facebook_user:
# facebook_app_id:                                #enter your App ID
# facebook_locale: en_US
# facebook_page:                                  #the URL of your Facebook Page
# facebook_image: images/author.jpg                      #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
# twitter_user: 
# twitter_card: true
# twitter_image: images/author.jpg                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
